---
title: "Data Science and Data Engineering Jan 2010-Dec 2016"
output:
  pdf_document: default
 # html_notebook: default
---


```{r setup, include=FALSE}
library(ggplot2)
library(zoo)
library(grid)
library(tscount)
library(svglite)
library(scales)
### Specify the file path and replace its name inside the parenthesis
myfile <- "file_name.csv"
total <- read.csv(myfile, header=TRUE)

total$Date <- as.yearmon(paste(total$yyyy, total$mon), "%Y %m")
total$Date <- as.Date(total$Date)



theme_white <- function() {
new_theme_empty <- theme_bw()
new_theme_empty$line <- element_blank()
new_theme_empty$rect <- element_blank()
new_theme_empty$strip.text <- element_blank()
new_theme_empty$axis.text <- element_blank()
new_theme_empty$plot.title <- element_blank()
new_theme_empty$axis.title <- element_blank()
new_theme_empty$plot.margin <- structure(c(0, 0, -1, -1), unit = "lines", valid.unit = 3L, class = "unit")
}

theme_set(theme_bw())
theme_white()


  g <- ggplot(total, aes(Date, jobs)) +
  scale_x_date(labels = date_format("%Y"),breaks = date_breaks("1 year")) +
 # scale_y_continuous(breaks = c(100, 500,1000,1500,2000,2500)) +
   # coord_trans(y = 'log10') +
    scale_y_log10(labels = comma,breaks=c(1,10,1000,100000,1000000)) +
  geom_line(data=total,aes(Date, JobsAll),show_legend=TRUE, color="black") +
  geom_line(data=total,aes(Date, JobsDSDE),show_legend=TRUE) +
    geom_line(data=total,aes(Date, JobsDS),show_legend=TRUE, color="darkred") +
    geom_line(data=total,aes(Date, JobsDE),show_legend=TRUE, color="darkblue") +
    geom_line(data=total,aes(Date, Pubs),show_legend=TRUE, color="darkgreen") +
    geom_point(data=total,aes(Date, MOOC),show_legend=TRUE,shape=4) +
    geom_point(data=total,aes(Date, IU_DE),show_legend=TRUE,shape=4) +
    geom_point(data=total,aes(Date, IU_DS),show_legend=TRUE,shape=4) +
    geom_point(data=total,aes(Date, Other_DS),show_legend=TRUE,shape=4) +
  xlab("Year") + ylab("Log 10 (Count)") +
annotate("text", x = total$Date[4], y = 101000, cex=3.5,label = "All Jobs") +
    annotate("text", x = total$Date[15], y = 3000000, cex=3.5,color="darkgreen",label = "Web of Science Publications") +
annotate("text", x = total$Date[14], y = 5, cex=3.5, color="darkred",label = "Data Scientist Job") +
 annotate("text", x = total$Date[50], y = 100, cex=3.5,color="darkblue",label = "Data Engineer Job") +
 annotate("text", x = total$Date[65], y = 6000, cex=3.5,color="black",label = "Data Scientist and Data Engineer Jobs") + 
     annotate("text", x = total$Date[70], y = 500, cex=2.5, color="black",label = "MOOC") +
    annotate("text", x = total$Date[73], y = 130, cex=2.5,color="black",label = "Other DS courses") +
    annotate("text", x = total$Date[73], y = 60, cex=2.5,color="black",label = "IU DS courses") +
    annotate("text", x = total$Date[73], y = 30, cex=2.5,color="black",label = "IU ISE courses") +
       theme_classic()+
  theme(plot.title = element_text(hjust = 0.5)) +
    theme(plot.title = element_text(hjust = 0.5),
axis.text.x=element_text(size=10),axis.text.y=element_text(size=10),
        panel.border = element_rect(colour = "black", fill=NA, size=0.71)) +
  theme(legend.position = c(0.15, 0.8))
  
  
 ### To save image, uncomment the line 73 or 74
#ggsave(g, device ="png", file="jobs_course_pubs_per_month.png")
#ggsave(g, device ="svg", file="jobs_dsde_per_month.svg")
```



```{r echo=FALSE,message=FALSE}

suppressWarnings(print(g))
```
